import type { Dictionary } from "./types";

export const en: Dictionary = {
  locale: "en",
  meta: {
    title: "Andriatiana Jean-Marie — Freelance Full Stack Developer | React, Next.js, NestJS, React Native",
    description:
      "Freelance Full Stack developer (5+ years) building SaaS products, booking platforms, Stripe payments and React Native mobile apps. React, Next.js, NestJS, AWS. Remote and available for your project.",
    keywords: [
      "freelance full stack developer",
      "hire React developer",
      "freelance Next.js developer",
      "NestJS developer",
      "freelance React Native developer",
      "Node.js TypeScript developer",
      "custom SaaS development",
      "booking platform developer",
      "Stripe integration developer",
      "mobile app development",
      "AWS Terraform developer",
      "remote software developer",
      "offshore developer Madagascar",
      "French-speaking developer",
      "LLM AI integration",
      "Claude Code MCP",
    ],
    ogAlt: "Andriatiana Jean-Marie — Freelance Full Stack Developer",
  },
  nav: {
    skip: "Skip to content",
    links: [
      { href: "#services", label: "Services" },
      { href: "#work", label: "Work" },
      { href: "#ai", label: "AI" },
      { href: "#experience", label: "Experience" },
      { href: "#process", label: "Process" },
      { href: "#faq", label: "FAQ" },
    ],
    cta: "Start a project",
    menu: "Open menu",
    theme: "Toggle theme",
    langLabel: "Language",
  },
  hero: {
    status: "Available for new freelance projects",
    titleBefore: "I design and ship your ",
    titleHighlight: "SaaS, web & mobile apps",
    titleAfter: " — from idea to production.",
    lead:
      "**Freelance Full Stack developer** with 5+ years of experience, specialized in **React, Next.js, NestJS, React Native and AWS**. I help startups, SMBs and agencies launch reliable products: booking platforms, Stripe payments, multi-tenant SaaS and mobile apps.",
    ctaPrimary: "Let's talk about your project",
    ctaSecondary: "See my work",
    meta: [
      { icon: "pin", text: "Remote from Madagascar" },
      { icon: "clock", text: "UTC+3 · overlaps with European hours" },
      { icon: "zap", text: "Reply within 24 h" },
    ],
    terminalTitle: "claude-code — milestone-run",
    terminal: [
      { text: '$ claude /milestone-run "Booking MVP"', tone: "prompt" },
      { text: "› Milestone: 6 tickets · dependency order resolved", tone: "dim" },
      { text: "› #42 Real-time booking slots", tone: "info" },
      { text: "  ✓ isolated git worktree", tone: "ok" },
      { text: "  ✓ tests written first (TDD) · 18 new", tone: "ok" },
      { text: "  ✓ NestJS + Next.js implementation", tone: "ok" },
      { text: "  ✓ browser QA (Playwright MCP)", tone: "ok" },
      { text: "  ✓ adversarial code review", tone: "ok" },
      { text: "  ✓ PR #87 · CI green · merged", tone: "purple" },
      { text: "› #43 Stripe payment (authorize → capture)…", tone: "warn" },
    ],
    profileRole: "Full Stack · Web & Mobile",
  },
  marquee: [
    "TypeScript", "React", "Next.js", "NestJS", "Node.js", "React Native", "Expo", "ASP.NET Core",
    "PostgreSQL", "Redis", "Stripe", "AWS", "Terraform", "Docker", "GitHub Actions", "Playwright", "Claude Code",
  ],
  stats: [
    { value: 5, suffix: "+", label: "years of freelance experience" },
    { value: 7, label: "clients served remotely" },
    { value: 10, suffix: "+", label: "products designed and shipped" },
    { value: 1767, label: "automated tests on a single project" },
  ],
  services: {
    eyebrow: "Services",
    title: "What I can build for you",
    text: "One partner for frontend, backend, mobile and cloud. You get speed, consistency and peace of mind.",
    items: [
      {
        icon: "layers",
        title: "SaaS & web applications",
        text: "From MVP to multi-tenant platform: architecture, frontend, backend and deployment.",
        points: ["Next.js / React, server rendering and SEO", "Multi-tenancy, roles and permissions", "Dashboards and back offices"],
        ideal: "Startups · SaaS companies · SMBs",
      },
      {
        icon: "calendar",
        title: "Booking & payments",
        text: "Hotels, spas, travel, ticketing: reliable booking engines and secure payments.",
        points: ["Stripe: payments, subscriptions, refunds, commissions", "Real-time availability and time slots", "Amadeus API, email / SMS notifications"],
        ideal: "Hospitality · wellness · travel · events",
      },
      {
        icon: "phone",
        title: "Mobile apps",
        text: "iOS & Android apps with React Native / Expo, connected to your API and ready for the stores.",
        points: ["Geolocation, push notifications, payments", "No-code → custom app migration", "Mobile E2E testing (Maestro)"],
        ideal: "Marketplaces · field apps · consumer apps",
      },
      {
        icon: "server",
        title: "APIs & backend",
        text: "Secure, documented and tested REST and GraphQL APIs, designed to scale with you.",
        points: ["NestJS, Node.js, ASP.NET Core", "Clean Architecture, BFF, modular monolith", "JWT auth, OpenAPI, real-time"],
        ideal: "Growing products · third-party integrations",
      },
      {
        icon: "cloud",
        title: "Cloud, DevOps & CI/CD",
        text: "Reproducible AWS infrastructure and automated deployments, from dev to prod.",
        points: ["AWS: ECS Fargate, RDS, Lambda, S3, CloudFront", "Terraform, Docker, nginx", "GitHub Actions, GitLab CI"],
        ideal: "Teams that want to ship often, stress-free",
      },
      {
        icon: "sparkles",
        title: "AI & automation",
        text: "LLM features inside your product and automation of your business workflows.",
        points: ["Sentiment analysis, generated replies (LLM)", "OCR and data extraction (Google Vision)", "Claude Code agents and MCP servers"],
        ideal: "Productivity gains · AI-powered products",
      },
    ],
  },
  projects: {
    eyebrow: "Work",
    title: "Real products, running in production",
    text: "A selection of projects showing how I solve concrete business problems with solid technical choices.",
    items: [
      {
        id: "spa",
        visual: "spa",
        icon: "flower",
        tag: "SaaS · Multi-tenant",
        metric: "0",
        metricLabel: "double bookings, guaranteed by PostgreSQL + a Redis lock",
        meta: ["Team project · TMap-Works", "2026 – ongoing", "580+ commits"],
        title: "Spa & Salon Booking",
        pitch:
          "Online booking SaaS for spas and salons: service catalog, practitioner choice, real-time slots, calendar, CRM, checkout and reporting.",
        points: [
          "**NestJS modular monolith** with 8 business modules and shared front/back API contracts.",
          "**Zero double bookings**: PostgreSQL exclusion constraint (tstzrange) plus a Redis lock, covered by concurrency tests.",
          "**AWS infrastructure in Terraform**: 14 modules, 3 environments, multi-AZ ECS Fargate, CloudFront + WAF.",
          "**Industrialized delivery**: 12 GitHub Actions workflows, SQS → Lambda → SES notifications, 17 ADRs.",
        ],
        stack: ["NestJS", "Next.js 15", "TypeScript", "PostgreSQL 16", "Redis", "Stripe", "AWS", "Terraform", "Playwright"],
      },
      {
        id: "stay",
        visual: "hotel",
        icon: "building",
        tag: "SaaS PMS · Marketplace",
        metric: "4",
        metricLabel: "apps: PMS API, BFF, marketplace and back office",
        meta: ["Personal project", "2025 – ongoing", "4 GitHub repositories"],
        title: "Stay — Hotel PMS & booking",
        pitch:
          "A multi-hotel SaaS PMS and a consumer marketplace: search → booking → payment → confirmation.",
        points: [
          "**ASP.NET Core 9 PMS API** following Clean Architecture: EF Core, PostgreSQL, JWT, OpenAPI.",
          "**BFF pattern with NestJS 11**: the Next.js 15 frontend never calls the PMS; secrets stay server-side.",
          "**Reliable Stripe payments**: authorize then capture, idempotency, reconciliation, PCI SAQ-A compliant.",
          "**Bilingual back office** (fr/en), multi-currency, WCAG 2.1 AA; k6, OWASP ZAP and Playwright testing.",
        ],
        stack: ["ASP.NET Core 9", "C#", "NestJS 11", "Next.js 15", "React 19", "Redis", "Stripe", "Docker", "k6"],
      },
      {
        id: "goltfork",
        visual: "golt",
        icon: "truck",
        tag: "Mobile · Marketplace",
        metric: "1,767",
        metricLabel: "automated tests: Jest, Supertest, RTL and Maestro",
        meta: ["Shipped to production", "2 Android apps"],
        title: "GoltFork — food truck marketplace",
        pitch: "Two mobile apps (buyer and vendor) backed by a NestJS API, designed and delivered end to end.",
        points: [
          "**Stripe payments**: checkout, subscriptions and automatic refunds when a vendor declines an order.",
          "**Menu import via OCR** (Google Vision) and SIRET verification through the INSEE Sirene API.",
          "**Full CI/CD**: GitHub Actions → GHCR → Docker VPS behind nginx.",
        ],
        stack: ["React Native", "Expo", "Zustand", "NestJS", "Prisma", "PostgreSQL", "Stripe", "Google Vision", "Docker"],
      },
      {
        id: "ngo",
        visual: "ngo",
        icon: "shield",
        tag: "Web platform · Impact",
        metric: "5",
        metricLabel: "criteria behind a public transparency score for each NGO",
        meta: ["In production", "Institutional donors & Malagasy NGOs"],
        title: "Paika — NGO certification platform",
        pitch: "A trust platform between institutional donors and NGOs: certification, transparency and online donations.",
        points: [
          "**Nuxt 3 + Supabase** with financial data isolated by Row-Level Security.",
          "**Encrypted document vault** and certification back office (Kanban, timestamped audit trail).",
          "**Stripe donations** with automatic commission and anonymized internal messaging.",
        ],
        stack: ["Nuxt 3", "Vue 3", "TypeScript", "Supabase", "PostgreSQL", "Stripe", "Tailwind CSS", "Playwright"],
      },
    ],
    gallery: { open: "View screenshots", close: "Close", prev: "Previous screenshot", next: "Next screenshot", of: "of" },
    moreTitle: "Also",
    more: [
      { icon: "message", title: "Spylebook", text: "Real-time social network: React, GraphQL Subscriptions, Prisma." },
      { icon: "users", title: "HR Management", text: "Leave and payroll management: ASP.NET Core, C#, Next.js." },
      { icon: "trophy", title: "HIU Hackathon 2023 — 2nd place", text: "E-commerce platform with 3D product visualization." },
    ],
  },
  ai: {
    eyebrow: "AI-augmented development",
    title: "Ship faster without cutting corners",
    text: "I built my own agentic development pipeline with Claude Code and MCP. Every ticket follows an automated path with strict quality gates, from requirement to merged pull request.",
    benefits: [
      "**Shorter delivery cycles**: more value in every sprint.",
      "**Every change is tested** (TDD), verified in a real browser and reviewed before merge.",
      "**Full traceability**: a run log posted on every GitHub ticket.",
      "**Strict guardrails**: no force-push, no skipped checks, secrets redacted.",
    ],
    steps: [
      { title: "GitHub ticket", detail: "Scoped requirement, dependencies analyzed", badge: "plan" },
      { title: "Isolated worktree", detail: "A dedicated branch, no side effects", badge: "git" },
      { title: "TDD development", detail: "Tests are written before the code", badge: "tdd" },
      { title: "Browser QA", detail: "Real checks with Playwright MCP", badge: "qa" },
      { title: "Code review", detail: "Adversarial review by a dedicated agent", badge: "review" },
      { title: "PR & auto-merge", detail: "Merged only when CI is green", badge: "ci ✓" },
    ],
  },
  experience: {
    eyebrow: "Experience",
    title: "Freelance work on real products",
    text: "Since 2022, I have worked remotely with companies on web and mobile products running in production.",
    jobs: [
      {
        period: "03/2025 — present",
        duration: "Freelance · Remote",
        role: "Full Stack Developer",
        company: "Glib Corporation",
        sector: "Travel booking platform",
        points: [
          "Payment and subscription module with Stripe.",
          "Amadeus API integration: hotels, flights and itineraries.",
          "Scheduled jobs and order lifecycle in NestJS; Docker + GitLab CI deployment.",
        ],
        stack: ["NestJS", "Prisma", "PostgreSQL", "Stripe", "Amadeus", "Docker", "GitLab CI"],
      },
      {
        period: "03/2024 — 01/2026",
        duration: "Freelance · Remote",
        role: "Full Stack Developer",
        company: "Digitalia LTD",
        sector: "CRM and AI for the construction industry",
        points: [
          "Custom CRM and dynamic forms for construction professionals.",
          "React Native mobile app for on-site project tracking.",
          "LLM (Gemini) for customer email sentiment analysis and generated replies.",
        ],
        stack: ["React", "React Native", "Node.js", "PostgreSQL", "Gemini", "Docker", "GitHub Actions"],
      },
      {
        period: "04/2024 — 01/2026",
        duration: "Freelance · Remote",
        role: "Full Stack Developer",
        company: "MDCL",
        sector: "Sports ticketing and seat management",
        points: [
          "Online ticketing platform: tickets, season passes and seat management.",
          "Real-time sales dashboard for event organizers.",
        ],
        stack: ["React", "Next.js", "NestJS", "MongoDB", "GitHub Actions"],
      },
      {
        period: "11/2024 — 01/2025",
        duration: "Freelance · Remote",
        role: "Mobile Developer",
        company: "Doci",
        sector: "Location-based mobile app",
        points: [
          "Migrated a no-code app to a custom React Native (Expo) app.",
          "Native geolocation to show nearby venues.",
        ],
        stack: ["React Native", "Expo", "Laravel", "PostgreSQL"],
      },
      {
        period: "09/2023 — 02/2024",
        duration: "Freelance · Remote",
        role: "Frontend Developer",
        company: "OnlyTravaux",
        sector: "PWA for the construction industry",
        points: [
          "Site-tracking PWA plus Directory and InfoTravaux modules.",
          "Defined business processes with industry professionals.",
        ],
        stack: ["React", "Vite", "TypeScript", "Jest", "Laravel"],
      },
      {
        period: "01/2023 — 08/2023",
        duration: "Contract",
        role: "Full Stack Developer",
        company: "The 23 Creative",
        sector: "Construction app and back office",
        points: [
          "Customer-tracking back office and the related client app.",
          "AWS administration (EC2, S3) and GitLab CI continuous deployment.",
        ],
        stack: ["Vue.js", "Laravel", "MySQL", "AWS", "GitLab CI"],
      },
      {
        period: "09/2022 — 08/2023",
        duration: "Contract",
        role: "Full Stack Developer",
        company: "Siooka",
        sector: "Restaurant SaaS (ordering and QR codes)",
        points: [
          "Ordering, invoicing and QR-code tickets.",
          "Per-restaurant theme customization from the back office.",
        ],
        stack: ["React", "TypeScript", "GraphQL", "Node.js", "AWS"],
      },
    ],
  },
  process: {
    eyebrow: "Process",
    title: "A simple, transparent collaboration",
    text: "You always know where your project stands. No black box: regular demos and full access to the code.",
    steps: [
      { title: "Discovery call", text: "30 minutes to understand your goals, your users and your constraints.", time: "Free · no commitment" },
      { title: "Scope & quote", text: "Scope, architecture, milestone-based plan and a detailed quote.", time: "Within 48 h" },
      { title: "Iterative build", text: "Short sprints, weekly demos, access to the repository and a staging environment.", time: "1–2 week sprints" },
      { title: "Launch & support", text: "Automated deployment, documentation, handover, then maintenance if needed.", time: "Post-launch support" },
    ],
  },
  why: {
    eyebrow: "Why work with me",
    title: "What you actually get",
    items: [
      {
        icon: "layers",
        title: "One partner, end to end",
        text: "Web, mobile, API and cloud: no juggling between vendors, one consistent vision of your product.",
      },
      {
        icon: "calendar",
        title: "Booking & payments expertise",
        text: "I know the traps: double bookings, payment idempotency, time zones, data isolation between tenants.",
      },
      {
        icon: "check",
        title: "Measurable quality",
        text: "Automated tests, CI/CD, code reviews and documented decisions (ADRs). Your product stays maintainable.",
      },
      {
        icon: "clock",
        title: "Europe-friendly hours",
        text: "Based in Madagascar (UTC+3), 1–2 hours ahead of Paris and London. Fluent French, working English.",
      },
    ],
  },
  stack: {
    eyebrow: "Tech stack",
    title: "Modern tools, proven in production",
    text: "I pick the technology for your needs, not the other way around.",
    groups: [
      { title: "Frontend", key: ["React", "Next.js", "TypeScript"], other: ["Vue.js", "Nuxt 3", "Angular", "Tailwind CSS", "Zustand", "TanStack Query", "Zod"] },
      { title: "Backend", key: ["Node.js", "NestJS", "ASP.NET Core", "Stripe"], other: ["Laravel", "GraphQL", "REST", "Prisma", "EF Core", "JWT"] },
      { title: "Mobile", key: ["React Native", "Expo"], other: ["Expo Router", "EAS", "Ionic", "PWA", "Maestro"] },
      { title: "Data", key: ["PostgreSQL", "Redis"], other: ["MongoDB", "MySQL", "Supabase", "Row-Level Security"] },
      { title: "Cloud & DevOps", key: ["AWS", "Docker", "Terraform"], other: ["GitHub Actions", "GitLab CI", "nginx", "Vercel", "Netlify"] },
      { title: "Quality & AI", key: ["Playwright", "Jest", "Claude Code"], other: ["Vitest", "k6", "OWASP ZAP", "xUnit", "MCP", "Gemini"] },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Frequently asked questions",
    items: [
      {
        q: "Do you work with clients in Europe and abroad?",
        a: "Yes. I work 100% remotely from Madagascar (UTC+3), only 1–2 hours ahead of Paris and London. I have worked remotely with French-speaking and international companies, with regular video check-ins.",
      },
      {
        q: "What kind of engagements do you take?",
        a: "Fixed-price projects (MVP, full platform, mobile app), team augmentation, taking over or extending an existing product, and maintenance. I adapt to your workflow (Scrum, Kanban, Jira, Taiga, GitHub Projects).",
      },
      {
        q: "How much does a project cost?",
        a: "It depends on the scope. After a free discovery call, I send a detailed quote split into milestones, so you stay in control of the budget at every step.",
      },
      {
        q: "Can you take over an existing project?",
        a: "Yes. I start with an audit (code, tests, deployment, security), secure what exists with tests and CI, then evolve the product without rewriting everything.",
      },
      {
        q: "You use AI — is my code reliable?",
        a: "AI speeds up the work, but every change goes through automated tests, browser verification, code review and CI. You fully own the code, and I am happy to sign an NDA.",
      },
      {
        q: "Do you offer maintenance after launch?",
        a: "Yes: bug fixes, security updates, new features and production monitoring, on a monthly retainer or on demand.",
      },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Got a project in mind? Let's talk.",
    text: "Tell me about your needs in a few lines. I reply within 24 hours with first ideas and a call proposal.",
    emailLabel: "Email",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    copy: "copy",
    copied: "Email address copied",
    cvLabel: "Download my resume (EN)",
    cvOther: "CV (FR)",
    form: {
      name: "Your name",
      namePh: "Jane Smith",
      email: "Your email",
      emailPh: "jane@company.com",
      type: "Project type",
      types: ["SaaS / web", "Booking & payments", "Mobile app", "API / backend", "Cloud & DevOps", "AI & automation", "Team augmentation"],
      budget: "Estimated budget",
      budgets: ["To be defined", "< $3,000", "$3,000 – 8,000", "$8,000 – 20,000", "$20,000 +"],
      timeline: "Timeline",
      timelines: ["Flexible", "ASAP", "Within 1 month", "1–3 months", "3+ months"],
      message: "Your project",
      messagePh: "Context, goals, key features, useful links…",
      submit: "Send my request",
      note: "The form opens your email app with a pre-filled message. No data is stored.",
      subject: "New project",
      bodyLabels: { name: "Name", email: "Email", type: "Project type", budget: "Budget", timeline: "Timeline" },
    },
  },
  footer: {
    rights: "All rights reserved.",
    built: "Designed and built with Next.js & TypeScript.",
    top: "Back to top",
  },
};
