import type { Dictionary } from "./types";

export const fr: Dictionary = {
  locale: "fr",
  meta: {
    title: "Andriatiana Jean-Marie — Développeur Full Stack Freelance | React, Next.js, NestJS, React Native",
    description:
      "Développeur Full Stack freelance (5+ ans) : SaaS, plateformes de réservation, paiements Stripe et applications mobiles React Native. React, Next.js, NestJS, AWS. En remote, disponible pour vos projets.",
    keywords: [
      "développeur full stack freelance",
      "développeur freelance React",
      "développeur Next.js freelance",
      "développeur NestJS",
      "développeur React Native freelance",
      "développeur Node.js TypeScript",
      "création SaaS sur mesure",
      "plateforme de réservation en ligne",
      "intégration Stripe",
      "développement application mobile",
      "développeur AWS Terraform",
      "développeur freelance remote",
      "développeur freelance Madagascar",
      "développeur francophone offshore",
      "intégration IA LLM",
      "Claude Code MCP",
    ],
    ogAlt: "Andriatiana Jean-Marie — Développeur Full Stack Freelance",
  },
  nav: {
    skip: "Aller au contenu",
    links: [
      { href: "#services", label: "Services" },
      { href: "#work", label: "Réalisations" },
      { href: "#ai", label: "IA" },
      { href: "#experience", label: "Parcours" },
      { href: "#process", label: "Méthode" },
      { href: "#faq", label: "FAQ" },
    ],
    cta: "Démarrer un projet",
    menu: "Ouvrir le menu",
    theme: "Changer de thème",
    langLabel: "Langue",
  },
  hero: {
    status: "Disponible pour de nouvelles missions freelance",
    titleBefore: "Je conçois et livre vos ",
    titleHighlight: "SaaS, apps web & mobiles",
    titleAfter: " — de l'idée à la production.",
    lead:
      "Développeur **Full Stack freelance** depuis plus de 5 ans, spécialisé en **React, Next.js, NestJS, React Native et AWS**. J'aide startups, PME et agences à lancer des produits fiables : plateformes de réservation, paiements Stripe, SaaS multi-tenant et applications mobiles.",
    ctaPrimary: "Discutons de votre projet",
    ctaSecondary: "Voir mes réalisations",
    meta: [
      { icon: "pin", text: "Remote depuis Madagascar" },
      { icon: "clock", text: "UTC+3 · horaires compatibles Europe" },
      { icon: "zap", text: "Réponse sous 24 h" },
    ],
    terminalTitle: "claude-code — milestone-run",
    terminal: [
      { text: '$ claude /milestone-run "MVP Booking"', tone: "prompt" },
      { text: "› Jalon : 6 tickets · ordre des dépendances résolu", tone: "dim" },
      { text: "› #42 Créneaux de réservation en temps réel", tone: "info" },
      { text: "  ✓ worktree git isolé", tone: "ok" },
      { text: "  ✓ tests écrits d'abord (TDD) · 18 nouveaux", tone: "ok" },
      { text: "  ✓ implémentation NestJS + Next.js", tone: "ok" },
      { text: "  ✓ QA navigateur (Playwright MCP)", tone: "ok" },
      { text: "  ✓ revue de code adversariale", tone: "ok" },
      { text: "  ✓ PR #87 · CI verte · fusionnée", tone: "purple" },
      { text: "› #43 Paiement Stripe (autorisation → capture)…", tone: "warn" },
    ],
    profileRole: "Full Stack · Web & Mobile",
  },
  marquee: [
    "TypeScript", "React", "Next.js", "NestJS", "Node.js", "React Native", "Expo", "ASP.NET Core",
    "PostgreSQL", "Redis", "Stripe", "AWS", "Terraform", "Docker", "GitHub Actions", "Playwright", "Claude Code",
  ],
  stats: [
    { value: 5, suffix: "+", label: "années d'expérience en freelance" },
    { value: 7, label: "clients accompagnés en remote" },
    { value: 10, suffix: "+", label: "produits conçus et mis en production" },
    { value: 1767, label: "tests automatisés sur un seul projet" },
  ],
  services: {
    eyebrow: "Services",
    title: "Ce que je peux construire pour vous",
    text: "Un seul interlocuteur pour le front, le back, le mobile et le cloud. Vous gagnez en vitesse, en cohérence et en sérénité.",
    items: [
      {
        icon: "layers",
        title: "SaaS & applications web",
        text: "Du MVP à la plateforme multi-tenant : architecture, front, back et mise en production.",
        points: ["Next.js / React, rendu serveur et SEO", "Multi-tenant, rôles et permissions", "Tableaux de bord et back-offices"],
        ideal: "Startups · éditeurs SaaS · PME",
      },
      {
        icon: "calendar",
        title: "Réservation & paiement",
        text: "Hôtels, spas, voyages, billetterie : des moteurs de réservation fiables et des paiements sécurisés.",
        points: ["Stripe : paiements, abonnements, remboursements, commissions", "Disponibilités et créneaux en temps réel", "API Amadeus, notifications e-mail / SMS"],
        ideal: "Hôtellerie · bien-être · tourisme · événementiel",
      },
      {
        icon: "phone",
        title: "Applications mobiles",
        text: "Apps iOS & Android en React Native / Expo, connectées à votre API et prêtes pour les stores.",
        points: ["Géolocalisation, notifications push, paiements", "Migration no-code → app sur mesure", "Tests E2E mobiles (Maestro)"],
        ideal: "Marketplaces · apps terrain · grand public",
      },
      {
        icon: "server",
        title: "API & backend",
        text: "Des API REST et GraphQL sécurisées, documentées et testées, pensées pour évoluer.",
        points: ["NestJS, Node.js, ASP.NET Core", "Clean Architecture, BFF, monolithe modulaire", "Auth JWT, OpenAPI, temps réel"],
        ideal: "Produits en croissance · intégrations tierces",
      },
      {
        icon: "cloud",
        title: "Cloud, DevOps & CI/CD",
        text: "Une infrastructure AWS reproductible et des déploiements automatisés, de dev à prod.",
        points: ["AWS : ECS Fargate, RDS, Lambda, S3, CloudFront", "Terraform, Docker, nginx", "GitHub Actions, GitLab CI"],
        ideal: "Équipes qui veulent livrer souvent, sans stress",
      },
      {
        icon: "sparkles",
        title: "IA & automatisation",
        text: "Intégration de LLM dans vos produits et automatisation de vos processus métier.",
        points: ["Analyse de sentiment, réponses générées (LLM)", "OCR et extraction de données (Google Vision)", "Agents Claude Code et serveurs MCP"],
        ideal: "Gain de productivité · produits augmentés",
      },
    ],
  },
  projects: {
    eyebrow: "Réalisations",
    title: "Des produits réels, en production",
    text: "Une sélection de projets qui montrent comment je résous des problèmes métier concrets, avec des choix techniques solides.",
    items: [
      {
        id: "spa",
        visual: "spa",
        icon: "flower",
        tag: "SaaS · Multi-tenant",
        metric: "0",
        metricLabel: "double réservation, garanti par PostgreSQL + verrou Redis",
        meta: ["Projet d'équipe · TMap-Works", "2026 – en cours", "580+ commits"],
        title: "Spa & Salon Booking",
        pitch:
          "SaaS de réservation en ligne pour spas et salons : catalogue, choix du praticien, créneaux en temps réel, agenda, CRM, encaissement et reporting.",
        points: [
          "**Monolithe modulaire NestJS** de 8 modules métier, avec contrats d'API partagés front / back.",
          "**Zéro double réservation** : contrainte d'exclusion PostgreSQL (tstzrange) et verrou Redis, couverts par des tests de concurrence.",
          "**Infrastructure AWS en Terraform** : 14 modules, 3 environnements, ECS Fargate multi-AZ, CloudFront + WAF.",
          "**Livraison industrialisée** : 12 workflows GitHub Actions, notifications SQS → Lambda → SES, 17 ADR.",
        ],
        stack: ["NestJS", "Next.js 15", "TypeScript", "PostgreSQL 16", "Redis", "Stripe", "AWS", "Terraform", "Playwright"],
      },
      {
        id: "stay",
        visual: "hotel",
        icon: "building",
        tag: "PMS SaaS · Marketplace",
        metric: "4",
        metricLabel: "applications : API PMS, BFF, marketplace et back-office",
        meta: ["Projet personnel", "2025 – en cours", "4 dépôts GitHub"],
        title: "Stay — PMS hôtelier & réservation",
        pitch:
          "Un PMS SaaS multi-hôtels et une place de marché grand public : recherche → réservation → paiement → confirmation.",
        points: [
          "**API PMS en ASP.NET Core 9** selon la Clean Architecture : EF Core, PostgreSQL, JWT, OpenAPI.",
          "**Pattern BFF en NestJS 11** : le front Next.js 15 n'appelle jamais le PMS, les secrets restent côté serveur.",
          "**Paiements Stripe fiables** : autorisation puis capture, idempotence, réconciliation, conformité PCI SAQ-A.",
          "**Back-office bilingue** fr/en, multi-devise, accessible WCAG 2.1 AA ; tests k6, OWASP ZAP et Playwright.",
        ],
        stack: ["ASP.NET Core 9", "C#", "NestJS 11", "Next.js 15", "React 19", "Redis", "Stripe", "Docker", "k6"],
      },
      {
        id: "goltfork",
        visual: "golt",
        icon: "truck",
        tag: "Mobile · Marketplace",
        metric: "1 767",
        metricLabel: "tests automatisés : Jest, Supertest, RTL et Maestro",
        meta: ["Livré en production", "2 applications Android"],
        title: "GoltFork — marketplace de food trucks",
        pitch: "Deux applications mobiles (acheteur et vendeur) reliées à une API NestJS, conçues et livrées de bout en bout.",
        points: [
          "**Paiements Stripe** : paiement, abonnement et remboursement automatique si le vendeur refuse la commande.",
          "**Import de menus par OCR** (Google Vision) et vérification SIRET via l'API INSEE Sirene.",
          "**CI/CD complète** : GitHub Actions → GHCR → VPS Docker derrière nginx.",
        ],
        stack: ["React Native", "Expo", "Zustand", "NestJS", "Prisma", "PostgreSQL", "Stripe", "Google Vision", "Docker"],
      },
      {
        id: "ngo",
        visual: "ngo",
        icon: "shield",
        tag: "Plateforme web · Impact",
        metric: "5",
        metricLabel: "critères pour un score de transparence public par ONG",
        meta: ["En production", "Bailleurs & ONG malgaches"],
        title: "Paika — certification d'ONG",
        pitch: "Une plateforme de confiance entre bailleurs institutionnels et ONG : certification, transparence et dons en ligne.",
        points: [
          "**Nuxt 3 + Supabase** avec cloisonnement des données financières par Row-Level Security.",
          "**Coffre-fort documentaire chiffré** et back-office de certification (Kanban, piste d'audit horodatée).",
          "**Dons Stripe** avec commission automatique et messagerie interne anonymisée.",
        ],
        stack: ["Nuxt 3", "Vue 3", "TypeScript", "Supabase", "PostgreSQL", "Stripe", "Tailwind CSS", "Playwright"],
      },
    ],
    gallery: { open: "Voir les captures", close: "Fermer", prev: "Capture précédente", next: "Capture suivante", of: "sur" },
    moreTitle: "Et aussi",
    more: [
      { icon: "message", title: "Spylebook", text: "Réseau social temps réel : React, GraphQL Subscriptions, Prisma." },
      { icon: "users", title: "RH Management", text: "Gestion des congés et de la paie : ASP.NET Core, C#, Next.js." },
      { icon: "trophy", title: "Hackathon HIU 2023 — 2e place", text: "Plateforme e-commerce avec visualisation 3D des produits." },
    ],
  },
  ai: {
    eyebrow: "Développement augmenté par l'IA",
    title: "Livrer plus vite, sans sacrifier la qualité",
    text: "J'ai conçu ma propre chaîne de développement agentique avec Claude Code et MCP. Chaque ticket suit un parcours automatisé, avec des portes qualité strictes, du besoin jusqu'à la pull request fusionnée.",
    benefits: [
      "**Des cycles de livraison plus courts** : plus de valeur à chaque sprint.",
      "**Chaque changement est testé** (TDD), vérifié dans le navigateur et relu avant fusion.",
      "**Traçabilité complète** : un journal d'exécution publié sur chaque ticket GitHub.",
      "**Des garde-fous stricts** : pas de push forcé, pas de vérification contournée, secrets masqués.",
    ],
    steps: [
      { title: "Ticket GitHub", detail: "Besoin cadré, dépendances analysées", badge: "plan" },
      { title: "Worktree isolé", detail: "Une branche dédiée, aucun effet de bord", badge: "git" },
      { title: "Développement TDD", detail: "Les tests sont écrits avant le code", badge: "tdd" },
      { title: "QA navigateur", detail: "Vérification réelle via Playwright MCP", badge: "qa" },
      { title: "Revue de code", detail: "Revue adversariale par un agent dédié", badge: "review" },
      { title: "PR & merge automatique", detail: "Fusion uniquement si la CI est verte", badge: "ci ✓" },
    ],
  },
  experience: {
    eyebrow: "Parcours",
    title: "Des missions freelance sur des produits réels",
    text: "Depuis 2022, j'accompagne des entreprises en remote sur des projets web et mobiles en production.",
    jobs: [
      {
        period: "03/2025 — aujourd'hui",
        duration: "Freelance · Remote",
        role: "Développeur Full Stack",
        company: "Glib Corporation",
        sector: "Plateforme de réservation de voyages",
        points: [
          "Module de paiement et d'abonnement avec Stripe.",
          "Intégration de l'API Amadeus : hôtels, vols et itinéraires.",
          "Tâches planifiées et cycle de vie des commandes côté NestJS ; déploiement Docker + GitLab CI.",
        ],
        stack: ["NestJS", "Prisma", "PostgreSQL", "Stripe", "Amadeus", "Docker", "GitLab CI"],
      },
      {
        period: "03/2024 — 01/2026",
        duration: "Freelance · Remote",
        role: "Développeur Full Stack",
        company: "Digitalia LTD",
        sector: "CRM et IA pour le secteur du bâtiment",
        points: [
          "CRM sur mesure et formulaires dynamiques pour les professionnels du bâtiment.",
          "Application mobile React Native de suivi de chantier.",
          "LLM (Gemini) pour analyser le sentiment des e-mails clients et générer des réponses.",
        ],
        stack: ["React", "React Native", "Node.js", "PostgreSQL", "Gemini", "Docker", "GitHub Actions"],
      },
      {
        period: "04/2024 — 01/2026",
        duration: "Freelance · Remote",
        role: "Développeur Full Stack",
        company: "MDCL",
        sector: "Billetterie sportive et gestion de places",
        points: [
          "Plateforme de billetterie en ligne : billets, abonnements et gestion des places.",
          "Tableau de bord des ventes en temps réel pour les organisateurs.",
        ],
        stack: ["React", "Next.js", "NestJS", "MongoDB", "GitHub Actions"],
      },
      {
        period: "11/2024 — 01/2025",
        duration: "Freelance · Remote",
        role: "Développeur Mobile",
        company: "Doci",
        sector: "Application mobile géolocalisée",
        points: [
          "Migration d'une application no-code vers une app React Native (Expo) sur mesure.",
          "Géolocalisation native pour afficher les terrains à proximité.",
        ],
        stack: ["React Native", "Expo", "Laravel", "PostgreSQL"],
      },
      {
        period: "09/2023 — 02/2024",
        duration: "Freelance · Remote",
        role: "Développeur Frontend",
        company: "OnlyTravaux",
        sector: "PWA pour le secteur du bâtiment",
        points: [
          "PWA de suivi de chantier et modules Annuaires / InfoTravaux.",
          "Définition des processus métier avec les professionnels du secteur.",
        ],
        stack: ["React", "Vite", "TypeScript", "Jest", "Laravel"],
      },
      {
        period: "01/2023 — 08/2023",
        duration: "Mission",
        role: "Développeur Full Stack",
        company: "The 23 Creative",
        sector: "Application bâtiment et back-office",
        points: [
          "Back-office de suivi client et application cliente associée.",
          "Administration AWS (EC2, S3) et déploiement continu GitLab CI.",
        ],
        stack: ["Vue.js", "Laravel", "MySQL", "AWS", "GitLab CI"],
      },
      {
        period: "09/2022 — 08/2023",
        duration: "Mission",
        role: "Développeur Full Stack",
        company: "Siooka",
        sector: "SaaS de restauration (commandes et QR codes)",
        points: [
          "Prise de commande, facturation et tickets QR code.",
          "Personnalisation des thèmes par restaurant depuis le back-office.",
        ],
        stack: ["React", "TypeScript", "GraphQL", "Node.js", "AWS"],
      },
    ],
  },
  process: {
    eyebrow: "Méthode",
    title: "Une collaboration simple et transparente",
    text: "Vous savez toujours où en est votre projet. Pas d'effet tunnel : des démos régulières et un accès permanent au code.",
    steps: [
      { title: "Appel découverte", text: "30 minutes pour comprendre vos objectifs, vos utilisateurs et vos contraintes.", time: "Gratuit · sans engagement" },
      { title: "Cadrage & devis", text: "Périmètre, architecture, planning par jalons et devis détaillé.", time: "Sous 48 h" },
      { title: "Développement itératif", text: "Sprints courts, démo chaque semaine, accès au dépôt et à un environnement de test.", time: "Sprints de 1 à 2 semaines" },
      { title: "Mise en production", text: "Déploiement automatisé, documentation, passation, puis maintenance si besoin.", time: "Suivi après livraison" },
    ],
  },
  why: {
    eyebrow: "Pourquoi travailler avec moi",
    title: "Ce que vous gagnez concrètement",
    items: [
      {
        icon: "layers",
        title: "Un seul interlocuteur, de bout en bout",
        text: "Web, mobile, API et cloud : pas de coordination entre plusieurs prestataires, une vision cohérente du produit.",
      },
      {
        icon: "calendar",
        title: "L'expertise réservation & paiement",
        text: "Je connais les pièges : double réservation, idempotence des paiements, fuseaux horaires, isolation des données entre clients.",
      },
      {
        icon: "check",
        title: "Une qualité mesurable",
        text: "Tests automatisés, CI/CD, revues de code et décisions documentées (ADR). Votre produit reste maintenable.",
      },
      {
        icon: "clock",
        title: "Des horaires compatibles avec l'Europe",
        text: "Basé à Madagascar (UTC+3), soit 1 à 2 h d'avance sur Paris. Communication fluide en français.",
      },
    ],
  },
  stack: {
    eyebrow: "Stack technique",
    title: "Des outils modernes, maîtrisés en production",
    text: "Je choisis la technologie selon votre besoin, pas l'inverse.",
    groups: [
      { title: "Frontend", key: ["React", "Next.js", "TypeScript"], other: ["Vue.js", "Nuxt 3", "Angular", "Tailwind CSS", "Zustand", "TanStack Query", "Zod"] },
      { title: "Backend", key: ["Node.js", "NestJS", "ASP.NET Core", "Stripe"], other: ["Laravel", "GraphQL", "REST", "Prisma", "EF Core", "JWT"] },
      { title: "Mobile", key: ["React Native", "Expo"], other: ["Expo Router", "EAS", "Ionic", "PWA", "Maestro"] },
      { title: "Données", key: ["PostgreSQL", "Redis"], other: ["MongoDB", "MySQL", "Supabase", "Row-Level Security"] },
      { title: "Cloud & DevOps", key: ["AWS", "Docker", "Terraform"], other: ["GitHub Actions", "GitLab CI", "nginx", "Vercel", "Netlify"] },
      { title: "Qualité & IA", key: ["Playwright", "Jest", "Claude Code"], other: ["Vitest", "k6", "OWASP ZAP", "xUnit", "MCP", "Gemini"] },
    ],
  },
  faq: {
    eyebrow: "FAQ",
    title: "Questions fréquentes",
    items: [
      {
        q: "Travaillez-vous avec des clients en France et en Europe ?",
        a: "Oui. Je travaille 100 % en remote depuis Madagascar (UTC+3), soit 1 à 2 h de décalage avec Paris. J'ai déjà accompagné à distance des entreprises francophones et internationales, avec des points réguliers en visio.",
      },
      {
        q: "Quels types de missions acceptez-vous ?",
        a: "Projets au forfait (MVP, plateforme complète, application mobile), renfort d'équipe en régie, reprise ou évolution d'un projet existant, et maintenance. Je m'adapte à votre organisation (Scrum, Kanban, Jira, Taiga, GitHub Projects).",
      },
      {
        q: "Combien coûte un projet ?",
        a: "Cela dépend du périmètre. Après un appel découverte gratuit, je vous envoie un devis détaillé, découpé en jalons, pour que vous gardiez le contrôle du budget à chaque étape.",
      },
      {
        q: "Pouvez-vous reprendre un projet existant ?",
        a: "Oui. Je commence par un audit (code, tests, déploiement, sécurité), je sécurise l'existant avec des tests et une CI, puis je fais évoluer le produit sans tout réécrire.",
      },
      {
        q: "Vous utilisez l'IA : mon code est-il fiable ?",
        a: "L'IA accélère le travail, mais chaque changement passe par des tests automatisés, une vérification dans le navigateur, une revue de code et la CI. Le code vous appartient intégralement et je peux signer un accord de confidentialité (NDA).",
      },
      {
        q: "Proposez-vous la maintenance après la livraison ?",
        a: "Oui : corrections, mises à jour de sécurité, nouvelles fonctionnalités et surveillance de la production, au forfait mensuel ou à la demande.",
      },
    ],
  },
  contact: {
    eyebrow: "Contact",
    title: "Un projet en tête ? Parlons-en.",
    text: "Décrivez votre besoin en quelques lignes. Je vous réponds sous 24 h avec de premières pistes et une proposition d'appel.",
    emailLabel: "E-mail",
    linkedinLabel: "LinkedIn",
    githubLabel: "GitHub",
    copy: "copier",
    copied: "Adresse e-mail copiée",
    cvLabel: "Télécharger mon CV (FR)",
    cvOther: "Resume (EN)",
    form: {
      name: "Votre nom",
      namePh: "Jean Dupont",
      email: "Votre e-mail",
      emailPh: "jean@entreprise.com",
      type: "Type de projet",
      types: ["SaaS / web", "Réservation & paiement", "App mobile", "API / backend", "Cloud & DevOps", "IA & automatisation", "Renfort d'équipe"],
      budget: "Budget estimé",
      budgets: ["À définir", "< 3 000 €", "3 000 – 8 000 €", "8 000 – 20 000 €", "20 000 € +"],
      timeline: "Délai souhaité",
      timelines: ["Flexible", "Dès que possible", "Sous 1 mois", "1 à 3 mois", "3 mois +"],
      message: "Votre projet",
      messagePh: "Contexte, objectifs, fonctionnalités clés, liens utiles…",
      submit: "Envoyer ma demande",
      sending: "Envoi en cours…",
      note: "Vos informations servent uniquement à vous répondre.",
      subject: "Nouveau projet",
      successTitle: "Merci, votre demande est bien envoyée !",
      successText: "Je vous réponds sous 24 h avec de premières pistes et une proposition d'appel.",
      again: "Envoyer une autre demande",
      error: "L'envoi a échoué. Réessayez dans un instant ou écrivez-moi directement :",
      bodyLabels: { name: "Nom", email: "E-mail", type: "Type de projet", budget: "Budget", timeline: "Délai" },
    },
  },
  footer: {
    rights: "Tous droits réservés.",
    built: "Conçu et développé avec Next.js & TypeScript.",
    top: "Retour en haut",
  },
};
